NativeAOT-LLVM: rewrite local vars to shadow stack
dotnet/runtimelab pull request #1658
Opened 2021-10-16 19:43 UTC by yowl

This PR addresses the comment from https://github.com/dotnet/runtimelab/pull/1649#discussion_r728334303.  It replaces local vars `GT_STORE_LCL_VAR` and `GT_LCL_VAR` with `GT_STORE_OBJ/GT_STOREIND` and `GT_OBJ/GT_IND` where the local is, or contains, gc references.  The replacement stores and load place the local on the shadow stack.  

Coverage is down slightly but not too worried about that as there are a couple of fixes for `TYP_LCLBLK` and `_info.compRetBuffArg != BAD_VAR_NUM` that probably account for it.

If optimisation is on then there is an additional call to `DoPhase(this, PHASE_MARK_LOCAL_VARS, &Compiler::lvaMarkLocalVars);` to get the local weights up to date, then a sort so that higher weighted locals are at the top of the stack.

2021-10-17 13:40 UTC, SingleAccretion requested changes
I think we need to figure out how to have the arguments be treated the same as locals (and temps), after all, the whole purpose of this is to remove this handling from codegen (i. e. get rid of `ValueLocation`).

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/compiler.cpp
> +    }
This doesn't look right - we're doing the refcounting twice. I would expect something more like this:
```c
if (opts.OptimizationEnabled())
    lvaMarkLocalVars(); // For optimization only
PlaceAndConvertShadowStackLocals();

lvaMarkLocalVars(); // For SSA i. e. correctness
fgSsaBuild();
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/compiler.cpp
> +    llvm->PlaceAndConvertShadowStackLocals();
It would be nice to plug `PlaceAndConvertShadowStackLocals` (and any new phases that come up) into the standard `DoPhase` phase mechanism, so that we get dumps at the end automatically.

The simple way to do that would be to use lambdas:
```cpp
auto placeAndConvertShadowStackLocalsPhase = [llvm]() {
    llvm->PlaceAndConvertShadowStackLocals();
}

DoPhase(this, PHASE_SHDWSTK_SETUP, placeAndConvertShadowStackLocalsPhase);
```
(You will also need to add `PHASE_SHDWSTK_SETUP` in `compphases.h`)

This is the "raw" way, without `PhaseStatus`, because there is `ActionPhase` which supports `PhaseStatus`, but it seems fine to have it be that way for the time being.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        // Use getClassAtribs over typGetObjLayout because EETypePtr has CORINFO_FLG_GENERIC_TYPE_VARIABLE? which fails with typGetObjLayout
Interesting. I wonder how that woks for the other targets (perhaps `EETypePtr` is treated as a "normed struct" there?).

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +Llvm::Llvm(Compiler* pCompiler)
Nit: we prefer member initializer lists for simple member initialization:
```cpp
Llvm::Llvm(Compiler* pCompiler)
    : _compiler(pCompiler)
    , _info(pCompiler->info)
    , /* and so on for other fields */
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +#if DEBUG
```suggestion
#ifdef DEBUG
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +GenTree* createAddNodeForShadowStackLocal(LclVarDsc* varDsc, unsigned shadowStackLclNum, GenTreeIntCon*& offset, GenTreeLclVar*& shadowStackVar)
I think it would be better to name this function `createShadowStackLocalAddress`, since that's what it does, and also move the insertion code here as well, it seem error-prone to create operands without inserting them into the range (the usual pattern for ranges, FWIW, it to have a "current range" field somewhere and an accessor function for it, so you don't have to pass it everywhere as an argument).

This would also get rid of the `out`-parameters through references, which are forbidden by out code convention (`out` parameters should use pointers).

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    offset->SetIconValue(varDsc->GetStackOffset());
Why not just:
```cpp
offset = _compiler->gtNewIconNode(varDsc->GetStackOffset(), TYP_I_IMPL);
// TYP_I_IMPL because it is a pointer offset.
```
?

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    shadowStackVar = _compiler->gtNewLclvNode(shadowStackLclNum, var_types::TYP_REF);
```suggestion
    shadowStackVar = _compiler->gtNewLclvNode(shadowStackLclNum, TYP_I_IMPL);
```
The shadow stack base itself is not an object reference...

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    return _compiler->gtNewOperNode(genTreeOps::GT_ADD, var_types::TYP_REF, shadowStackVar, offset);
```suggestion
    return _compiler->gtNewOperNode(GT_ADD, TYP_I_IMPL, shadowStackVar, offset);
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    unsigned shadowStackLclNum = _compiler->lvaGrabTemp(false, "shadowstack"); // TODO-LLVM: create a new local as a temp, is this right?  Copied from lower.cpp
> is this right

Yep.
```suggestion
    unsigned shadowStackLclNum = _compiler->lvaGrabTemp(true DEBUGARG("shadowstack"));
```
`true` because it "has long lifetime", though it doesn't actually matter (this was used a very long time ago by Pre-RyuJit "legacy" backend as a register allocator hint).

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    GenTreeIntCon* shadowStackArg = _compiler->gtNewOneConNode(var_types::TYP_UINT)->AsIntCon();
I would like to understand this.

What prevents us from making the shadow stack local refer to the base of the stack for all locals, including arguments? That is sort of the whole point of this, to get rid of handling this in codegen.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    shadowStackVarDsc->lvType = var_types::TYP_REF;
Ditto: the shadow stack should have `TYP_I_IMPL`.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        LIR::Range& lirRange = LIR::AsRange(block);
Probably the shorter `range` is enough, ranges are a LIR-only concept.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        for (GenTree* node : LIR::AsRange(block))
```suggestion
        for (GenTree* node : range)
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    genTreeOps oper = lclVar->TypeGet() == var_types::TYP_STRUCT ? GT_STORE_OBJ : GT_STOREIND;
```suggestion
                    genTreeOps oper = lclVar->TypeIs(TYP_STRUCT) ? GT_STORE_OBJ : GT_STOREIND;
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    GenTree* addNode = createAddNodeForShadowStackLocal(varDsc, shadowStackLclNum, offset, shadowStackVar);
(See the comments above about combining `createAddNodeForShadowStackLocal` with `insertAddWithOperands`, also, I would rename `addNode` to `lclAddress` (or something similar)).

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +            else if (oper == GT_LCL_VAR)
This code looks a bit repetitive, I wonder if we could deduplicate it with something like this:
```cpp
if (!node->OperIs(GT_LCL_VAR, GT_STORE_VAR))
{
    continue;
}

GenTreeLvlVarCommon* lclVar = ...;
// The varDsc, the createAddress call, etc

genTreeOps indirOper = GT_NONE:
switch (node->OperGet() { /* choose the new oper */ }

node->ChangeOper(indirOper);
node->AsIndir()->SetAddr(address);

if (GenTree::OperIsStore(indiOper)
{
   node->AsOp()->gtOp2 = storedValue;
}
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    }
This would go away with the proper phase integration.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        if (!varDsc->lvIsParam && !canStoreLocalOnLlvmStack(varDsc))
Ditto: what prevents us from laying out parameters as well?

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    std::vector<LclVarDsc*> locals;
Seems like `locals` are uninitialized here?

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    if (_compiler->lvaCount == 0) return;
```suggestion
    if (_compiler->lvaCount == 0)
    {
        return;
    }
```
A rare condition, but presumably can happen.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    if (locals.size() == 0) return;
```suggestion
    if (locals.size() == 0)
    {
        return;
    }
```

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        auto cmpLambda = [](const LclVarDsc* lhs, const LclVarDsc* rhs) { return lhs->lvRefCntWtd() > rhs->lvRefCntWtd(); };
You could inline this into the call if you want.

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +}
Ditto: the arguments & shadow stack.

What prevents us from, when seeing the shadow stack local node in the IR, map it to the shadow stack arg?

2021-10-17 13:40 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        if (varDsc->lvIsParam && !canStoreLocalOnLlvmStack(varDsc))
Ditto: the arguments & shadow stack.

2021-10-18 01:34 UTC, yowl commented
Thanks for the review so far.  I've included arguments now and removed the shadow stack setup logic as it's just arg 0 now.  I also moved most of the functions to class member.

I haven't removed `ValueLocation` yet as it's still on use for phi args and for return values.  Phi args can be done some other way, that should be easy.  Return values I'm not sure .  Do you have something I mind?

2021-10-18 10:36 UTC, SingleAccretion commented
>  I also moved most of the functions to class member.

(Very nice! Will also allow for getting rid much of the `IRBuilder` passing around)

>  Phi args can be done some other way, that should be easy.

(I've come to think that it will be easiest to not play tricks with them and just record every instance (`GT_PHI` node + the LLVM's `PHINode*`) in an array and then at the end of code generation "fill them in", since the locals map should have all the defs needed at that point)

>  Return values I'm not sure . Do you have something I mind?

Could you elaborate? I see we now return GC types by callee storing them to the shadow stack to an address passed by the caller. Presumably it should be easy enough to transform the following IR:
```scala
SDSU = CALL_REF(SS, ...)
```
To something we are actually going to generate:
```scala
// SS - the shadow stack local
// OFFSET is some reserved address on the shadow stack
CALL_REF(SS, SS + OFFSET, ...)
SDSU = IND(SS + OFFSET)
```
(I also see we're incrementing `OFFSET` currently by maintaining a stack of them - why is that necessary? Presumably callee returning frees the `OFFSET` slot on the shadow stack)
(Also we should transform all arguments passed via the shadow stack to explicit stores to the said stack)

And for the method itself returning, that should also presumably be straightforward:
```scala
RETURN(ref)
```
=>
```scala
STOREIND(RetSpillAddress aka Arg(1), ref)
RETURN(void)
```

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/compiler.cpp
> +        lvaMarkLocalVars(); // For optimization only
```suggestion
        // When optimizing, we'll sort the locals on the shadow stack by ref count.
        lvaMarkLocalVars();
```

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/compiler.cpp
> +    lvaMarkLocalVars();  // For SSA i. e. correctness
```suggestion
    lvaMarkLocalVars();  // For SSA.
```
Don't think there is a need to elaborate, the lack of `if (OptimizationEnabled())` implies that already.

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        GenTreeLclVar* shadowStackVar = _compiler->gtNewLclvNode(_shadowStackLclNum, var_types::TYP_I_IMPL);
```suggestion
        GenTreeLclVar* shadowStackVar = _compiler->gtNewLclvNode(_shadowStackLclNum, TYP_I_IMPL);
```

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        GenTree* lclAddress = _compiler->gtNewOperNode(genTreeOps::GT_ADD, var_types::TYP_I_IMPL, shadowStackVar, offset);
```suggestion
        GenTree* lclAddress = _compiler->gtNewOperNode(GT_ADD, TYP_I_IMPL, shadowStackVar, offset);
```

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +void Llvm::CreateShadowStackLocalAddress(GenTree* node)
Hmm I think the name has now become a misnomer as this both creates the address and does the rewriting. Proposed (another...) new name: `ConvertShadowStackLocalNode`.

I think this can also take `GenTreeLclVarCommon*` as the argument.

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +            break;
Nit: indentation needs to move one level to the right.

Nit:
```c
default:
    unreached();
```
needs to be added (some Unix compilers warn without it, so we always add it).

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        LIR::Range& currentRange = LIR::AsRange(block);
```suggestion
```
Unused.

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        _currentRange = &LIR::AsRange(block);
I think we can use the pre-existing `_currentBlock` here, it seems unlikely that we'll need to use scratch ranges as "current".

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    }
```suggestion
    for (unsigned lclNum = 0; lclNum < _compiler->lvaCount; lclNum++)
    {
        LclVarDsc* varDsc = _compiler->lvaGetDesc(lclNum);
        if (!canStoreLocalOnLlvmStack(varDsc))
        {
            locals.push_back(varDsc);
        }
    }
```

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    _sigInfoIsValid = true;
Get the sig info in the constructor? We'll need it anyway, so doesn't seem like lazy initialization is worth it.

2021-10-18 12:22 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    }
We'll be sorting all variables... but don't arguments need to be at fixed offsets?

2021-10-18 14:40 UTC, yowl commented
> Could you elaborate? I see we now return GC types by callee storing them to the shadow stack to an address passed by the caller. Presumably it should be easy enough to transform the following IR:
> 

> (I also see we're incrementing `OFFSET` currently by maintaining a stack of them - why is that necessary? Presumably callee returning frees the `OFFSET` slot on the shadow stack) (Also we should transform all arguments passed via the shadow stack to explicit stores to the said stack)
> 

In the IL->LLVM generation, the result of the call is placed in a spilled expression entry which is on the expressions stack.  I don't think its guaranteed that that will be popped before the next call.  The spilled expression stack is also used in a few other places, new arrays, exception slots, AddressOf (boxing),.  As there is no expression stack here, and I imagine exception/filters/finallys will be done differently I guess we can just delete the spilled slot stack in `llvm.cpp`

2021-10-18 16:46 UTC, yowl commented
> 
> ```scala
> // SS - the shadow stack local
> // OFFSET is some reserved address on the shadow stack
> CALL_REF(SS, SS + OFFSET, ...)
> SDSU = IND(SS + OFFSET)
> ```

I've a problem with generating this, obviously I'm not using the right methods.  I've tried to clone the call, and bash the original 
```scala
            else if (node->IsCall() && needsReturnStackSlot(_sigInfo.retType, _sigInfo.retTypeClass))
            {
                GenTreeCall* callClone = _compiler->gtCloneExpr(node)->AsCall();
                GenTreeLclVar* shadowStackVar = _compiler->gtNewLclvNode(_shadowStackLclNum, TYP_I_IMPL);
                GenTreeIntCon* offset = _compiler->gtNewIconNode(_shadowStackLocalsSize, TYP_I_IMPL);
                GenTree* retSlot = _compiler->gtNewOperNode(GT_ADD, TYP_I_IMPL, shadowStackVar, offset);
                _compiler->gtPrependNewCallArg(retSlot, callClone->gtCallArgs);

                var_types originalReturnType = callClone->TypeGet();
                callClone->ResetReturnType();
                callClone->gtReturnType = var_types::TYP_VOID;

                CurrentRange().InsertBefore(node, shadowStackVar);
                CurrentRange().InsertAfter(shadowStackVar, offset);
                CurrentRange().InsertAfter(offset, retSlot);
                CurrentRange().InsertAfter(retSlot, callClone);

                node->ChangeOper(originalReturnType == var_types::TYP_STRUCT ? GT_OBJ : GT_IND);
                node->AsOp()->gtOp1 = retSlot;
            }
```
But the resulting IR is not right: the return type has not changed to void, and the extra call arg is missing:
```scala
               [000211] ------------       t211 =    LCL_VAR   int    V14 tmp8         u:1
               [000212] ------------       t212 =    CNS_INT   int    24
                                                  /--*  t211   int
                                                  +--*  t212   int
               [000213] ------------       t213 = *  ADD       int
                                                  /--*  t206   int    arg0 in rcx
                                                  +--*  t207   ref    arg1 in rdx
     ( 20,  8) [000203] --CXG-------       t203 = *  CALL      ref    System.Runtime.TypeCast.CheckCastClass
                                                  /--*  t213   int
N005 ( 20,  8) [000040] --CXG-------        t40 = *  IND       ref
```
Where am I going wrong?

2021-10-18 17:06 UTC, SingleAccretion commented
I think in this case `LIR::TryGetUse` will be a better choice - cloning arbitrary calls is a badly tested path in the compiler. Something like:
```scala
// Set up the `retSlot`
// Prepend it to the existing call.
LIR::Use callUse;
if (CurrentRange().TryGetUse(call, &callUse))
{
    // Set up the `retSlot`, again (maybe a better name is returnValueAddress)...
    GenTree* returnedValue = gtNewIndir(retSlot, call->TypeGet());
    callUse.ReplaceWith(_compiler, returnedValue);
}
else
{
    call->ClearUnusedValue();
}

// Calls have *3* "return types" - the descriptor, which is irrelevant for us,
// the node's type and the gtReturnType, which we'll set.
call->gtReturnType = TYP_VOID;
call->ChangeType(TYP_VOID);
```

As to the original snippet, there were a few issues:

> the return type has not changed to void

The `gtType` was not changed.

> extra call arg is missing

Note that you're creating an SDSU, but using it in two places: the call's arg and the indirection. The dump is just showing that there is only one node inserted in the range.

2021-10-19 00:31 UTC, yowl commented
Thanks, I'm afraid that I've still not got the adding of the new call arg right.  I have now (created a temp for the 2 references to the return address)
```scala
                // replace the "CALL ref" with a "CALL void" that takes a return address as the first argument
                GenTreeCall* callNode = node->AsCall();
                var_types callReturnType = callNode->TypeGet();
                GenTreeLclVar* shadowStackVar = _compiler->gtNewLclvNode(_shadowStackLclNum, TYP_I_IMPL);
                GenTreeIntCon* offset = _compiler->gtNewIconNode(_shadowStackLocalsSize, TYP_I_IMPL);
                GenTree* returnValueAddress = _compiler->gtNewOperNode(GT_ADD, TYP_I_IMPL, shadowStackVar, offset);

                // create temp for the return address
                unsigned returnTempNum = _compiler->lvaGrabTemp(true, "return value address");
                LclVarDsc* returnAddrVarDsc = _compiler->lvaGetDesc(returnTempNum);
                returnAddrVarDsc->lvIsParam = 0;
                returnAddrVarDsc->lvType = var_types::TYP_I_IMPL;

                GenTree* addrStore = _compiler->gtNewStoreLclVar(returnTempNum, returnValueAddress);
                GenTree* returnAddrLcl = _compiler->gtNewLclvNode(returnTempNum, TYP_I_IMPL);
                
                callNode->gtCallArgs = _compiler->gtPrependNewCallArg(returnAddrLcl, callNode->gtCallArgs);
```
However this hits the assert https://github.com/dotnet/runtimelab/blob/1f26ea2d2d9514f3d9bb4d0b33a123ab2a63b055/src/coreclr/jit/gentree.cpp#L7204
If I add a breakpoint on the `gtPrependNewCallArg` line, there's a couple of things I dont understand about what I'm doing.  There's 2 args to this call `public static unsafe object CheckCastArray(MethodTable* pTargetEEType, object obj)`  an int and the ref.  

`callNode->gtCallArgs` is a nullptr, that sounds odd
![image](https://user-images.githubusercontent.com/2720041/137824062-cfcbe406-9e31-4445-a01a-f3344d184f3f.png)

But there is something in `gtCallLateArgs`.

`fgArgInfo.argCount` == 1:
![image](https://user-images.githubusercontent.com/2720041/137824148-67bfe99c-bf06-4352-a1f8-1512e547ad0b.png)

- When, if ever, should I be trying to update `gtCallLateArgs` and not `gtCallArgs`?
- Why is that not 2?
- Do I have to call something to rebuild `fgArgInfo` ?

The IR before I modify it is
```scala
N003 (  3,  2) [000058] ------------        t58 =    LCL_VAR   int    V00 arg0
N004 (  3,  2) [000059] ------------        t59 =    LCL_VAR   ref    V01 arg1
                                                  /--*  t58    int    arg0 in rcx
                                                  +--*  t59    ref    arg1 in rdx
N005 ( 20,  8) [000060] --CXG-------        t60 = *  CALL      ref    System.Runtime.TypeCast.CheckCastInterface
```
Thanks for all the help so far.

2021-10-19 14:03 UTC, SingleAccretion commented
I should have seen this coming...

> When, if ever, should I be trying to update gtCallLateArgs and not gtCallArgs?

It's messy. The short answer is updating either beyond morphing is not that well supported a scenario.

> Why is that not 2?

Honestly, I do not know, seems unexpected.

> Do I have to call something to rebuild `fgArgInfo` ?

In theory, you can call `ResetArgInfo` and then `fgInitArgInfo`. But the latter is likely not work properly for us (it does not know about the shadow stack and the spill slot). I suggest you try to it anyway for now, it is not in this PR that calls will be unraveled. If turns out not to work at all, I suggest punting the calls in this PR (and leaving the `LlvmLocation` in for now).

The proper fix for these problems is to rewrite all calls to:
1. Move all "late args" to the normal arg list. The "late args" list is an invention meant to control evaluation order of arguments in HIR, where use order _is_ the evaluation order. LIR has no such constraints. For the LLVM backend, it is doubly useless because we have no complicated register-not-register ABI requirements to abide by (for now at least).
2. Rebuild the arg info, aka just recreate it with the minimal necessary information. It will not be terribly useful anyway once we get rid of the late args.

2021-10-21 02:42 UTC, yowl commented
Your suggestion has worked, thanks!.  I've still to try to remote `LLVMLocation` but looks promising.  I just fail the compilation if there are non -late args which seems to work unless there are out args (which it doesn't do anyway yet).

2021-10-22 01:19 UTC, yowl commented
This is ready now, except for an issue with how to create `GT_STORE_OBJ ` nodes.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +      _shadowStackLclNum(-1),
```suggestion
      _shadowStackLclNum(BAD_VAR_NUM),
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +      _retAddressLclNum(-1)
```suggestion
      _retAddressLclNum(BAD_VAR_NUM)
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    shadowStackVarDsc->lvType = var_types::TYP_I_IMPL;
```suggestion
    shadowStackVarDsc->lvType = TYP_I_IMPL;
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                if (callNode->gtCallType == CT_HELPER || callNode->gtReturnType == var_types::TYP_VOID)
```suggestion
                if (callNode->IsHelperCall() || callNode->TypeIs(TYP_VOID))
```
`gtReturnType` is only really different for small typed calls.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    returnAddrVarDsc->lvIsParam = 0;
```suggestion
```
No need to set it explicitly as that's the default.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    returnAddrVarDsc->lvType = var_types::TYP_I_IMPL;
```suggestion
                    returnAddrVarDsc->lvType = TYP_I_IMPL;
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    GenTree* indirNode = _compiler->gtNewOperNode(callReturnType == var_types::TYP_STRUCT ? GT_OBJ : GT_IND, callReturnType, returnAddrLcl2);
```suggestion
                    GenTree* indirNode = _compiler->gtNewOperNode(callReturnType == TYP_STRUCT ? GT_OBJ : GT_IND, callReturnType, returnAddrLcl2);
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    unsigned returnTempNum = _compiler->lvaGrabTemp(true, "return value address");
```suggestion
                    unsigned returnTempNum = _compiler->lvaGrabTemp(false DEBUGARG("return value address"));
```
The heuristic here is "do we use the local in multiple blocks?". But actually it does not matter.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    callNode->gtReturnType = var_types::TYP_VOID;
```suggestion
                    callNode->gtReturnType = TYP_VOID;
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    GenTree* returnAddrLcl2 = _compiler->gtNewLclvNode(returnTempNum, TYP_I_IMPL);
Not a big fan of numbered locals... `returnAddrLclAfterCall` perhaps?

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    CurrentRange().InsertAfter(returnAddrLcl2, indirNode);
We have overloads for the insertion functions going up to 4 arguments, so you could shorten this (applies to other places too):
```
CurrentRange().InsertBefore(callNode, shadowStackVar, offset, returnValueAddress, addrStore);
CurrentRange().InsertAfter(callNode, returnAddrLcl2, indirNode);
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                assert(_retAddressLclNum == -1);
```suggestion
                assert(_retAddressLclNum == BAD_VAR_NUM);
```
Or probably just have a step before the LLVM phases that initializes the special locals.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                //TODO-LLVM: how to create a GT_STORE_OBJ node?
It seems we do not have a general helper, however, in this case `gtNewTempAssign` should be sufficient.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                retAddressVarDsc->lvType = var_types::TYP_I_IMPL;
```suggestion
                retAddressVarDsc->lvType = TYP_I_IMPL;
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                CurrentRange().InsertAfter(retAddressLocal, storeNode);
Succinct insert overloads apply.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +    std::vector<LclVarDsc*> locals;
```suggestion
    std::vector<LclVarDsc*> locals();
```
Initializing the `locals` local...

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +//
```suggestion
//------------------------------------------------------------------------
// Convert GT_STORE_LCL_VAR and GT_LCL_VAR to use the shadow stack when the local needs to be GC tracked,
// rewrite calls that returns GC types to do so via a store to a passed in address on the shadow stack.
// Likewise, store the returned value there if required.
//
```

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/compiler.h
> +#ifndef TARGET_WASM
I think it is better to `#ifdef` `public:` here, it is very unusual to see the declarations split like that.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +void Llvm::addForwardPhiArg(SsaPair ssaPair, llvm::Value* phiArg)
Now unused along with `_forwardReferencingPhis`.

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
>          case TYP_REF:
Presumably this is now `unreachable`?

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +        CurrentRange().InsertAfter(shadowStackVar, lclAddress);
Succinct insertion overloads (see comment below).

2021-10-22 06:27 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                        // TODO-LLVM: out args?  E.g.
FWIW, we'll not have them for arguments that LLVM will handle. For arguments that it does not handle (i. e. those that need to be on the shadow stack), we'll `STOREIND/OBJ` them to the said stack before the call.

2021-10-22 21:35 UTC, yowl commented
I've removed an assert to enable the creation of `GT_STORE_OBJ`.  Maybe I missed something obvious.  For the vector creation I left off the `()` as it didn't compile.  I left a picture in the review.  Again maybe I've just not understood c++'s intricacies here.

2021-10-22 21:48 UTC, SingleAccretion approved these changes
Just two comments, otherwise looks **great**!

2021-10-22 21:48 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    storeNode = originalReturnType == TYP_STRUCT
Hmm, I think you can leave only the `STOREIND` case here, since this is an unreachable branch: `if (originalReturnType == TYP_STRUCT) { if (originalReturnType == TYP_STRUCT) ... } }`.

2021-10-22 21:48 UTC, SingleAccretion commented on src/coreclr/jit/llvm.cpp
> +                    storeNode = _compiler->gtNewOperNode(GT_STORE_OBJ, originalReturnType, retAddressLocal, node->AsOp()->gtOp1);
Sorry for drifting in some unclear directions with the `gtNewTempAssign`...

The "normal" way to get a `ExOp` node is to use the construstor, i. e. do `new (_compiler, GT_STORE_OBJ) GenTreeObj(originalReturnType, retAddressLocal, node->AsOp()->gtGetOp1(), layout)` (may necessitate some massaging of the compiler with `::new` or `GenTree::new`.

2021-10-23 00:45 UTC, yowl commented
Thanks, these 2 bits corrected and the assert reinstated

2021-10-23 18:10 UTC, jkotas commented
@SingleAccretion Thank you for reviewing these changes!

2021-10-23 18:11 UTC, merged