[WIP] Add basic support projecting frozen structs
dotnet/runtimelab pull request #2560
Opened 2024-04-23 19:06 UTC by kotlarmilos

## Description

This PR is a work in progress, intended to collect early feedback from other contributors and allow other contributors to build on the top of this. It introduces Swift metadata types and implements basic support for frozen structs.

### Tasks

The following tasks needs to be done before making it ready for review:
 - [ ] Update `StructEmitter` method to support non-frozen structs
 - [ ] Implement type lookup via mangled name
 - [ ] Add Debug.Assert to check the type layout against the ABI file
 - [ ] Encapsulate metadata accessor naming logic in a helper method
 - [ ] Encapsulate constructor naming logic in a helper method
 - [ ] Verify and document all implemented types
 - [ ] Encapsulate _swiftToCSharpMapping and _swiftTypeInfo in a class/struct
 - [ ] The ABI parser should search for the type within this and imported modules and lazy-load it
 - [ ] Add tests
 - [ ] Update docs

2024-04-30 19:53 UTC, stephen-hawley reviewed
One thing you're going to run into in your code is that you don't have a distinction between a type declaration and a type specification. This will cause you problems later on.

Here's what the distinction is:
a type declaration is a nominal type in swift. It is anything that has a name and its public facing API. This includes top-level functions, structs, enums, classes, and actors.

A type specification is the annotation that is used to specify the type of a parameter, an associated type, a type alias target, or the return type of a method. In swift, a type specification can include nominal types (fully or partially specified), tuples, closure types, and protocol list types. In addition, parts of these types may include syntactic sugars such as option, implicitly unwrapped options, and meta information such as attributes. All of those elements need to be handled correctly.

Indeed, the representation of these types is, unto itself, a little language.

I strongly recommend that you take `TypeSpecParser`, `TypeSpecTokenizer`, `TypeSpecToken`, and `TypeSpec (and its subclasses). This represents a very compact recursive descent parser than can handle whatever the swift compiler can generate.

2024-05-16 10:54 UTC, kotlarmilos commented
I've converted this PR to draft as we plan to have additional iterations before another review. @stephen-hawley thank you for your contribution. Here are some thoughts:
- I like your approach with the conductor class and factories, but I don't see the value of having an additional layer on top of the declarations, such as `TypeEnv`, `MethodEnv`, and `ArgumentEnv`. I think we should operate with a single source of truth, which should be the declarations. Do you see anything missing in the declarations?
- I suggest moving handlers to emitters, as they actually emit code. Perhaps we can name them `{Name}Emitter`?
- Can we use `FieldDecl` instead of `ArgumentDecl`?
- It looks like the factory should replace `ModuleEmitter` and be invoked from `Program.cs`.
- I wonder if we can simplify `IFactory`. The codegen might bloat with such generics usage, and we may try to simplify it. I imagine that in most cases, we would rely on string representation and not actual generic types in the `IFactory` implementations.

Let's integrate your changes and add comments, documentation, and more test cases.

2024-05-16 12:55 UTC, kotlarmilos commented
> I strongly recommend that you take TypeSpecParser, TypeSpecTokenizer, TypeSpecToken, and `TypeSpec (and its subclasses). This represents a very compact recursive descent parser than can handle whatever the swift compiler can generate.

Let's add them in a follow-up PR as this one is already ~+5k loc. What is the difference between `TypeDecl` and `TypeSpec`?

2024-05-17 14:28 UTC, stephen-hawley requested changes

2024-05-17 14:28 UTC, stephen-hawley commented on src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
> +            return decl is TypeDecl && decl is ClassDecl;
`decl is TypeDecl &&` isn't needed. If the type is a `ClassDecl` it is always a `TypeDecl`

2024-05-17 14:28 UTC, stephen-hawley commented on src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
> +            return decl is TypeDecl && decl is StructDecl;
`decl is TypeDecl && ` isn't needed.

2024-05-17 14:28 UTC, stephen-hawley commented on src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
> +            foreach (BaseDecl baseDecl in structDecl.Declarations)
This should be done through the conductor, otherwise we will have identical code for classes, structs, enums, and actors when it could be in one place.

2024-05-17 14:43 UTC, kotlarmilos commented on src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
> +            foreach (BaseDecl baseDecl in structDecl.Declarations)
I created `BaseHandler` that implements `HandleBaseDecl` and calls into `Conductor`. Do you have any better ideas here?

2024-05-17 15:44 UTC, stephen-hawley commented on src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
> +            foreach (BaseDecl baseDecl in structDecl.Declarations)
How about putting an `EmitInnerTypes` method into `BaseHandler` which looks like:
```
protected EmitInnerTypes(IEnumerable<TypeDecl> types, IndentedTextWriter writer, Conductor conductor, TypeDatabase typeDatabase) {
    writer.Indent++;
    foreach (var type in types) {
        HandleBaseDecl(writer, baseDecl, conductor, typeDatabase);
    }
    writer.Indent--;
}
```

2024-05-17 16:50 UTC, kotlarmilos commented on src/Swift.Bindings/src/Emitter/StringCSharpEmitter/Handler/TypeHandler.cs
> +            foreach (BaseDecl baseDecl in structDecl.Declarations)
Moved the loop to the `HandleBaseDecl`. I didn't change the name of the method as it handles other declarations as well. We can rename it later.

2024-05-17 17:21 UTC, stephen-hawley approved these changes

2024-05-21 07:12 UTC, kotlarmilos commented
Merging this PR. Any additional feedback will be addressed in follow-up work.

2024-05-21 07:22 UTC, merged